on: [push, pull_request]

name: Tests

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --all-features

  lints:
    name: Lints
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      
      - run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings
    
  test:
    name: cargo test
    runs-on: ubuntu-latest
    needs:
      - lints
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features